name: Node.js CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Navigate to the project directory on the admin
            cd /var/www/html/millat/client

            # Fetch all updates from the remote repository
            git fetch --all

            # Reset the current branch to match the remote main branch
            git reset --hard origin/main

            # Ensure environment variables are set up correctly
            cp .example.env .env

            # Install necessary dependencies
            npm install

            # Build the project
            npm run build

            # Check if PM2 process exists, if so, restart it, otherwise start a new one
            if pm2 describe millat-client > /dev/null; then
              pm2 restart millat-client
            else
              pm2 start npm --name "millat-client" -- start
            fi

            # Save PM2 process list to ensure process persists
            pm2 save
